# Generated by Django 5.1.1 on 2024-11-05 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('imagen', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('mensaje', models.TextField()),
                ('asunto', models.CharField(max_length=200, null=True, verbose_name='Asunto')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripción de la Etiqueta')),
            ],
            options={
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='RegistroCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Correos de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, null=True)),
                ('detalle', models.TextField(max_length=2000, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/media')),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('pendiente', 'pendiente')], default='pendiente', max_length=20)),
                ('destacado', models.BooleanField(default=False)),
                ('conteo_visitas', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.autor')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.categoria')),
                ('etiquetas', models.ManyToManyField(blank=True, to='blog.etiqueta')),
            ],
            options={
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('cuerpo', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blog.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('cuerpo', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='blog.comentario')),
            ],
        ),
    ]
