# Generated by Django 5.1.1 on 2024-11-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_es_aprobado_comentario_es_aprobado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='es_aprobado',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='es_aprobado',
        ),
        migrations.AddField(
            model_name='comentario',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('aprobado', 'aprobado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='estado',
            field=models.CharField(choices=[('activo', 'activo'), ('pendiente', 'pendiente'), ('aprobado', 'aprobado')], default='pendiente', max_length=20),
        ),
    ]
